BROWSER = chrome
HEADLESS = true

EXPLICIT_WAIT_TIMEOUT = 10
HARD_WAIT_TIMEOUT = 2
STEP_TIME = 1
PAGE_LOAD_TIMEOUT = 60
API_TIMEOUT = 20

SCREENSHOT_PATH = ./exports/screenshots/
RECORD_VIDEO_PATH = ./exports/videos/
RECORD_VIDEO = yes
SCREENSHOT_STEP_ALL = no
EXTENT_REPORT_PATH = exports/ExtentReport/ExtentReport.html
EXTENT_REPORT_ZIP_PATH = exports/ExtentReport.zip
REPORT_TITLE = Report | Hybrid Automation Framework | Injas Mahendra Berutu

REPORT.ALLURE.ENABLED = true
REPORT.EXTENT.ENABLED = true

REPORT.EMAIL.ENABLED = false

ALLURE_REPORT_URL =

EMAIL.SMTP.HOST = smtp.gmail.com
EMAIL.SMTP.PORT = 587
EMAIL.FROM = injasmahendra123@gmail.com
EMAIL.PASSWORD =
EMAIL.TO= mahendraqa27@gmail.com

AUTHOR = Injas Mahendra Berutu
LOCATE = en