#Allure environment
#Wed Jul 08 10:54:55 WIB 2026
Account.Type=Production Account
Author=Injas Mahendra Berutu
Base.URL=https\://eventhub.rahulshettyacademy.com/login
Browser=chrome
Environment=prod
Executor=Local Machine (Injas Mahendra Berutu)
Headless.Mode=On
Java.Version=21.0.2
Locale=en
Maven.Profile.Env=prod
Operating.System=Windows
Test.User.Email=creola.vendervort@gmail.com
